In [180]:
%matplotlib inline
import numpy as np
import loompy
import cytograph as cg
import os
import logging
import matplotlib.pyplot as plt
import scipy.cluster.hierarchy as hc

with loompy.connect("/Users/sten/build_20171205/L5_All.agg.loom") as ds:
    data = ds[:,:]
    nnz = np.count_nonzero(data, axis=1)
    data = data[(nnz > 100), :]
    genes = ds.ra.Gene[(nnz > 100) ]
    data = np.log(data + 1)

In [181]:
data.shape

(14041, 265)

In [147]:
d = hc.linkage(data, metric="euclidean")

In [159]:
labels = hc.fcluster(d, t=0.9)
labels.max()

7468

In [160]:
np.unique(np.bincount(labels))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 17,
       18, 20, 22, 25, 27, 29, 31, 34, 40, 41, 44])

(array([1148]),)

In [167]:
ix = np.where(np.bincount(labels)==34)[0]
for i in ix:
    print(np.sort(genes[labels==i]))

['1700026J14Rik' '4933430I17Rik' 'A230060F14Rik' 'A530053M12Rik' 'Ccdc38'
 'Cfd' 'Elf5' 'Fcer2a' 'Fut7' 'Gm11592' 'Gm11998' 'Gm14061' 'Gm15939'
 'Gm17552' 'Gm26530' 'Gm26783' 'Gm42512' 'Gm831' 'Gm9918' 'Hhipl1' 'Hif3a'
 'Hist1h4a' 'Kcna7' 'Klk1b3' 'Mpo' 'Rnf151' 'Rnf39' 'Serpina11' 'Slc27a5'
 'Synpo2l' 'Tmc1' 'Tmem184a' 'Tmprss4' 'Zfp97']
['1700047I17Rik2' '4933408N05Rik' 'Aadat' 'Amh' 'Fbxo48' 'Gjd4' 'Gm10184'
 'Gm10226' 'Gm10489' 'Gm12925' 'Gm14420' 'Gm14493' 'Gm15894' 'Gm21083'
 'Gm26548' 'Gm3448' 'Gm3512' 'Gm35986' 'Gm42809' 'Gm43604' 'Gm43796'
 'Gm648' 'Gm6793' 'Gm7293' 'Klk7' 'Lrrc66' 'Lrrc8e' 'Mageb16' 'Nphs2'
 'Pou5f1' 'Prr22' 'RP23-235M8.7' 'Tmem254c' 'Zscan10']


In [169]:
labels[genes=="Gad2"]

array([], dtype=int32)

In [130]:
ix[0]

array([1148])